### ISSUE TITLE
Feature test for in_journey? method

### ISSUE THREAD

**Issue by Reeshul** [Reeshul/Oystercard#1]
```
:001 > card = Oystercard.new
 => #<Oystercard:0x00007f808517d9c0 @balance=0> 
 :002 > card.in_journey?
```

```NoMethodError (undefined method `in_journey?' for #<Oystercard:0x00007f808517d9c0 @balance=0>)```

Next step: Create a unit test so that the `in_journey?` method responds to an instance of the Oystercard class.

**Comment by twigz826** [comment]
Resolved through creating a method `in_journey?`. Two other methods were created: `touch_in` and `touch_out` and an instance variable to track the status was created in the `initialize` method.
